---

#
##
# role.skel - Role Skeleton template     
# 
# Example Logic Block "block, rescue, always" Ansible Logic is built in
# Meant to emulate Java "try catch" logic block
# Modify Logic Block according to your role
# Delete Variable definitions below that are not used in your role
##
#

- block:
  - name: check if directory exists
    stat:  
      path: /root/buildbot
    register: output  
  
  - debug: var=output 
    when: playbook_debug 

  - assert:
      that: output.stat.exists == true 

  rescue:
  - name: clone the example repository
    command: chdir=/root git clone --depth 1 https://github.com/buildbot/buildbot-docker-example-config
    register: output
 
  - debug: var=output
    when: playbook_debug

  - assert:
      that: output.changed == true

  - name: stat buildbot-docker-example-config
    stat: path=/root 
    register: docker_stat

  - debug: var=docker_stat
    when: playbook_debug

  - name: rename the buildbot-example-config directory
    command: chdir=/root cp -r buildbot-docker-example-config buildbot
    when: docker_stat.stat.exists

  - name: delete original example directory
    file: path=/root/buildbot-docker-example-config state=absent
    when: docker_stat.stat.exists

  - name: make directory
    file:
      path: /root/buildbot/simple/config
      state: directory
    register: directory

  - debug: var=directory
    when: playbook_debug

  always:    
  - name: replace master.cfg file with master.cfg.js 
    become_user: root
    template:
      src: master.cfg.j2
      dest: "/root/buildbot/simple/config/master.cfg"
    register: output

  - debug: var=output
    when: playbook_debug

  - name: deploy the docker container
    command: chdir=/root/buildbot/simple docker-compose up -d
    register: deployment

  - debug: var=deployment 
    when: playbook_debug
